sonar.organization=lymonoficial
sonar.projectKey=Lymonoficial_lymon-backend
sonar.projectName=lymon-backend

#sonar.projectKey=lymon
#sonar.projectName=lymon
sonar.projectVersion=1.0
#sonar.token=yourtoken
sonar.host.url=https://sonarcloud.io
#sonar.host.url=http://localhost:9000

sonar.sources=src,performance/k6
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/seeds/**,**/.scannerwork/**,**/.git/**
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/*.module.ts,**/seeds/**
sonar.sourceEncoding=UTF-8

