sonar.projectKey=Lymonoficial_lymon-backend
sonar.projectName=lymon-backend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
# sonar.token=${env.SONAR_TOKEN}

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=\
  test/application/incident-report/create-incident-report.handler.spec.ts,\
  test/application/incident-report/get-incident-reports-by-property.query-handler.spec.ts,\
  test/application/incident-report/update-incident-report.handler.spec.ts,\
  test/application/tenant/update-tenant-profile.handler.spec.ts,\
  test/application/tenant/get-tenant-profile.query-handler.spec.ts,\
  test/infrastructure/auth/guards/jwt-auth.guard.spec.ts,\
  test/infrastructure/auth/guards/permission.guard.spec.ts,\
  test/presentation/controllers/incident-report.controller.spec.ts,\
  test/presentation/controllers/tenant.controller.spec.ts,\
  test/infrastructure/persistence/repositories/mongo-incident-report.repository.spec.ts,\
  test/infrastructure/persistence/repositories/mongo-tenant.repository.spec.ts,\
  test/domain/tenant/value-objects/plan-type.vo.spec.ts

sonar.typescript.lcov.reportPaths=coverage/scope/lcov.info
sonar.javascript.lcov.reportPaths=coverage/scope/lcov.info

sonar.inclusions=\
  src/application/incident-report/commands/create-incident-report.handler.ts,\
  src/application/incident-report/commands/update-incident-report.handler.ts,\
  src/application/incident-report/queries/GetIncidentReportsByProperty/get-incident-reports-by-property.query-handler.ts,\
  src/application/tenant/commands/update-tenant-profile.handler.ts,\
  src/application/tenant/queries/GetTenantProfile/get-tenant-profile.query-handler.ts,\
  src/domain/incident-report/entities/incident-report.entity.ts,\
  src/domain/incident-report/repositories/incident-report.repository.ts,\
  src/domain/incident-report/value-objects/incident-report-id.vo.ts,\
  src/domain/tenant/entities/tenant.entity.ts,\
  src/domain/tenant/repositories/tenant.repository.ts,\
  src/domain/tenant/value-objects/tenant-id.vo.ts,\
  src/domain/tenant/value-objects/plan-type.vo.ts,\
  src/infrastructure/persistence/repositories/mongo-incident-report.repository.ts,\
  src/infrastructure/persistence/repositories/mongo-tenant.repository.ts,\
  src/presentation/controllers/incident-report.controller.ts,\
  src/presentation/controllers/tenant.controller.ts,\
  src/infrastructure/auth/guards/jwt-auth.guard.ts,\
  src/infrastructure/auth/guards/permission.guard.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts,**/seeds/**
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/*.module.ts,**/seeds/**
sonar.sourceEncoding=UTF-8