export enum GuestPreferencePredefinedKeyEnum {
  // Dietary
  VEGAN = 'VEGAN',
  VEGETARIAN = 'VEGETARIAN',
  GLUTEN_FREE = 'GLUTEN_FREE',
  LOW_SUGAR = 'LOW_SUGAR',
  NUT_ALLERGY = 'NUT_ALLERGY',
  LACTOSE_FREE = 'LACTOSE_FREE',
  HALAL = 'HALAL',
  KOSHER = 'KOSHER',

  // Room
  HIGH_FLOOR = 'HIGH_FLOOR',
  LOW_FLOOR = 'LOW_FLOOR',
  QUIET_ROOM = 'QUIET_ROOM',
  SMOKING = 'SMOKING',
  NON_SMOKING = 'NON_SMOKING',
  EXTRA_PILLOWS = 'EXTRA_PILLOWS',
  FOAM_PILLOW = 'FOAM_PILLOW',
  FEATHER_PILLOW = 'FEATHER_PILLOW',
  EXTRA_BLANKET = 'EXTRA_BLANKET',

  // Accessibility
  HANDICAP_ACCESSIBLE = 'HANDICAP_ACCESSIBLE',
  WHEELCHAIR_ACCESSIBLE = 'WHEELCHAIR_ACCESSIBLE',
  ROLL_IN_SHOWER = 'ROLL_IN_SHOWER',
  GRAB_BARS = 'GRAB_BARS',
  VISUAL_ALERTS = 'VISUAL_ALERTS',
}
