export enum AuditAction {
  AUTH_LOGIN = 'AUTH_LOGIN',
  TENANT_REGISTERED = 'TENANT_REGISTERED',
  USER_INVITED = 'USER_INVITED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_EMAIL_VERIFIED = 'USER_EMAIL_VERIFIED',
  PROPERTY_CREATED = 'PROPERTY_CREATED',
  PROPERTY_UPDATED = 'PROPERTY_UPDATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  UNIT_CREATED = 'UNIT_CREATED',
  UNIT_UPDATED = 'UNIT_UPDATED',
  UNIT_DELETED = 'UNIT_DELETED',
}

export enum AuditEntityType {
  AUTH = 'AUTH',
  TENANT = 'TENANT',
  USER = 'USER',
  PROPERTY = 'PROPERTY',
  UNIT = 'UNIT',
}
